server:
  port: 7001
spring:
  application:
    name: consul-clent
  cloud:
    consul:
      host: 192.168.0.189 #consul的服务地址
      port: 8500         #consul的端口号
      discovery:
        register-health-check: false     #关闭服务健康检查
        service-name: ${spring.application.name} #指定服务名称