server:
  port: 9999  
spring:
  application:
    name: PMS
  cloud:
    consul:
      discovery:
        register-health-check: false #关闭健康检查
        service-name: ${spring.application.name} 
      port: 8500
      host: 192.168.0.189
PMS:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule    

