server:
  port: 9998
spring:
  application:
    name: UMS
  cloud:
    consul:
      discovery:
        register-health-check: false #关闭健康检查
        service-name: ${spring.application.name}
      port: 8500
      host: 192.168.0.189
      
feign:
  client:
    config:
      PMS:
        connectTimeout: 5000
        readTimeout:    5000      

