server:
  port: 7878
spring:
  application:
    name: config_server
  cloud:
    consul:
      host: 192.168.0.189
      port: 8500
    config:
      server:
        git:
          uri: https://gitee.com/wu-juxuan/configserver.git
          username: 100742869@qq.com
          password: Cc100742869.

    